// Generated by gencpp from file beginner_tutorials/NumArray.msg
// DO NOT EDIT!


#ifndef BEGINNER_TUTORIALS_MESSAGE_NUMARRAY_H
#define BEGINNER_TUTORIALS_MESSAGE_NUMARRAY_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <beginner_tutorials/Num.h>

namespace beginner_tutorials
{
template <class ContainerAllocator>
struct NumArray_
{
  typedef NumArray_<ContainerAllocator> Type;

  NumArray_()
    : window()  {
    }
  NumArray_(const ContainerAllocator& _alloc)
    : window(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector< ::beginner_tutorials::Num_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::beginner_tutorials::Num_<ContainerAllocator> >::other >  _window_type;
  _window_type window;




  typedef boost::shared_ptr< ::beginner_tutorials::NumArray_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::beginner_tutorials::NumArray_<ContainerAllocator> const> ConstPtr;

}; // struct NumArray_

typedef ::beginner_tutorials::NumArray_<std::allocator<void> > NumArray;

typedef boost::shared_ptr< ::beginner_tutorials::NumArray > NumArrayPtr;
typedef boost::shared_ptr< ::beginner_tutorials::NumArray const> NumArrayConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::beginner_tutorials::NumArray_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::beginner_tutorials::NumArray_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace beginner_tutorials

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'beginner_tutorials': ['/home/student/catkin_ws/src/beginner_tutorials/msg', '/home/student/catkin_ws/src/beginner_tutorials/msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::beginner_tutorials::NumArray_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::beginner_tutorials::NumArray_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::beginner_tutorials::NumArray_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::beginner_tutorials::NumArray_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::beginner_tutorials::NumArray_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::beginner_tutorials::NumArray_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::beginner_tutorials::NumArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "b201c82cac6bab33355fc0478375d517";
  }

  static const char* value(const ::beginner_tutorials::NumArray_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xb201c82cac6bab33ULL;
  static const uint64_t static_value2 = 0x355fc0478375d517ULL;
};

template<class ContainerAllocator>
struct DataType< ::beginner_tutorials::NumArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "beginner_tutorials/NumArray";
  }

  static const char* value(const ::beginner_tutorials::NumArray_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::beginner_tutorials::NumArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Num[] window\n\
\n\
================================================================================\n\
MSG: beginner_tutorials/Num\n\
int64 xpos\n\
int64 ypos\n\
";
  }

  static const char* value(const ::beginner_tutorials::NumArray_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::beginner_tutorials::NumArray_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.window);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct NumArray_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::beginner_tutorials::NumArray_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::beginner_tutorials::NumArray_<ContainerAllocator>& v)
  {
    s << indent << "window[]" << std::endl;
    for (size_t i = 0; i < v.window.size(); ++i)
    {
      s << indent << "  window[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::beginner_tutorials::Num_<ContainerAllocator> >::stream(s, indent + "    ", v.window[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // BEGINNER_TUTORIALS_MESSAGE_NUMARRAY_H
